# Generated by Django 5.1.3 on 2024-11-16 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='wariaciknauczyciel',
        ),
    ]
