# Generated by Django 5.1.3 on 2024-11-16 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='app_cars',
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='reservations_cars',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users_cars',
        ),
    ]
