# Generated by Django 5.1.3 on 2024-11-16 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0005_alter_car_table_alter_reservation_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservation',
            table='app_reservations',
        ),
        migrations.AlterModelTable(
            name='user',
            table='app_users',
        ),
    ]
